- name: variables precedence
  hosts: localhost
  vars_files:
  - variables.yaml
  vars:
   PERSON: "sowji from play"
   PASSWORD: "sowji123"
  tasks:
  - name: check variables
    ansible.builtin.debug:
     msg: "hello {{PERSON}}..........ur pwd is {{PASSWORD}}"

