- name: installing packages using loops
  hosts: localhost
  tasks:
  - name: installing packages
    ansible.builtin.package:
     name: "{{item}}"
     state: present
    loop:
    - git
    - postfix
    - mysql